URL1 = https://www.flipkart.com/
ProductName = iphone XR (64 GB) - Yellow

URL1 = https://amazon.in/
ProductName = iphone XR (64 GB) - Yellow

URL2 = https://admin-demo.nopcommerce.com/login?ReturnUrl=%2Fadmin%2F